// validations/booking.ts
// Generated by: Data Layer Intelligence Prompt

import { z } from 'zod';

export const createBookingSchema = z.object({
  serviceId:      z.string().uuid(),
  userId:         z.string().uuid().optional(),
  startsAt:       z.coerce.date().min(new Date(), { message: 'Start time must be in the future' }),
  endsAt:         z.coerce.date().optional(),
  paymentMethod:  z.string().min(1, { message: 'Payment method is required' }),
  mobileProvider: z.string().optional(),
  email:          z.string().email().optional(),
  userName:       z.string().min(1, { message: 'Name is required' }),
  phone:          z.string().min(10, { message: 'Valid phone number is required' }),
}).refine(data => {
  if (data.endsAt) {
    return data.endsAt > data.startsAt;
  }
  return true;
}, {
  message: 'End time must be after start time',
  path: ['endsAt'],
});

export const updateBookingSchema = z.object({
  startsAt: z.coerce.date().optional(),
  endsAt:   z.coerce.date().optional(),
  status:   z.enum(['CONFIRMED', 'CANCELLED']).optional(),
}).refine(data => {
  if (data.startsAt && data.endsAt) {
    return data.endsAt > data.startsAt;
  }
  return true;
}, {
  message: 'End time must be after start time',
  path: ['endsAt'],
});

export type CreateBookingInput = z.infer<typeof createBookingSchema>;
export type UpdateBookingInput = z.infer<typeof updateBookingSchema>;
