// types/booking.ts
// Generated by: Data Layer Intelligence Prompt
// Domain entity: Booking

import { User } from './user'; // Assume generated
import { Service } from './service'; // Assume generated

// ─── ENUMS ────────────────────────────────────────────────────────────────────

export type BookingStatus =
  | 'PENDING'
  | 'CONFIRMED'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'CANCELLED';

export const BOOKING_STATUSES: BookingStatus[] = [
  'PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'
];

export const BOOKING_STATUS_LABELS: Record<BookingStatus, string> = {
  PENDING:     'Pending',
  CONFIRMED:   'Confirmed',
  IN_PROGRESS: 'In Progress',
  COMPLETED:   'Completed',
  CANCELLED:   'Cancelled',
};

// Color assignment for semantic UI rendering
export const BOOKING_STATUS_COLORS: Record<BookingStatus, 'positive' | 'warning' | 'danger' | 'neutral'> = {
  PENDING:     'warning',
  CONFIRMED:   'positive',
  IN_PROGRESS: 'positive',
  COMPLETED:   'neutral',
  CANCELLED:   'danger',
};

// ─── BASE TYPE (matches DB row exactly) ──────────────────────────────────────

export interface Booking {
  id:             string;
  serviceId:      string;
  userId:         string | null;
  startsAt:       Date;
  endsAt:         Date | null;
  paymentMethod:  string;
  mobileProvider: string | null;
  email:          string | null;
  userName:       string;
  phone:          string;
  status:         BookingStatus;
  
  confirmedAt:    Date | null;
  cancelledAt:    Date | null;
  cancelledBy:    string | null;
  cancelReason:   string | null;
  completedAt:    Date | null;

  createdAt:      Date;
  updatedAt:      Date;
  deletedAt:      Date | null;
}

// ─── WITH RELATIONS (populated joins) ────────────────────────────────────────

export interface BookingWithUser extends Booking {
  user: Pick<User, 'id' | 'name' | 'email' | 'image'> | null;
}

export interface BookingWithService extends Booking {
  service: Pick<Service, 'id' | 'name' | 'price'>;
}

export interface BookingWithFull extends Booking {
  user:    User | null;
  service: Service;
  photos:  { id: string; url: string }[];
}

// ─── FORM / INPUT TYPES ───────────────────────────────────────────────────────

export interface CreateBookingInput {
  serviceId:      string;
  userId?:        string; // Optional for guests
  startsAt:       Date;
  endsAt?:        Date;
  paymentMethod:  string;
  mobileProvider?: string;
  email?:         string;
  userName:       string;
  phone:          string;
}

export interface UpdateBookingInput {
  startsAt?: Date;
  endsAt?:   Date;
  status?:   Extract<BookingStatus, 'CONFIRMED' | 'CANCELLED'>;
}

// ─── API RESPONSE TYPES ───────────────────────────────────────────────────────

export interface BookingListResponse {
  data:  BookingWithService[];
  meta: {
    total:   number;
    page:    number;
    limit:   number;
    hasMore: boolean;
  };
}

export interface BookingDetailResponse {
  data: BookingWithFull;
}
