// types/service.ts
// Generated by: Data Layer Intelligence Prompt
// Domain entity: Service

export interface Service {
  id:             string;
  name:           string;
  price:          number; // cents
  stripePriceId:  string | null;

  createdAt:      Date;
  updatedAt:      Date;
  deletedAt:      Date | null;
}
