// types/user.ts
// Generated by: Data Layer Intelligence Prompt
// Domain entity: User

export type UserRole = 
  | 'SUPER_ADMIN'
  | 'ADMIN'
  | 'STAFF'
  | 'CLIENT';

export interface User {
  id:                 string;
  name:               string | null;
  email:              string;
  emailVerified:      Date | null;
  role:               UserRole;
  phone:              string | null;
  image:              string | null;
  referralCode:       string | null;
  referredById:       string | null;
  referralPoints:     number;

  createdAt:          Date;
  updatedAt:          Date;
  deletedAt:          Date | null;
}
